---
free_packages:
  # BASE
  - base-devel
  - clang
  - fontconfig-devel
  - xtools
  # APPS
  - vim
  - htop
  - curl
  - git
  - neofetch
  - neovim
  - zsh
  - alacritty
  - anki 
  - telegram-desktop
  - Thunar
  - vscode
  - mpv
  - imv
  - qbittorrent
  - wget
  - syncthing
  - brightnessctl
  - pipewire
  - connman
  - pass
  - lazygit 
  # SWAY
  # Troubles:
  # https://www.reddit.com/r/voidlinux/comments/hgm4ig/void_sway_troubleshooting_reminder/
  # https://www.reddit.com/r/voidlinux/comments/nab764/sway_not_working/
  # https://github.com/swaywm/sway/wiki/Running-Sway-without-systemd
  # https://docs.voidlinux.org/config/graphical-session/graphics-drivers/index.html
  - dbus-elogind
  - polkit
  - elogind
  - mesa-dri
  - xorg-fonts
  - gvfs
  - wayland
  - sway
  - swaylock
  - Waybar

non_free_packages:
  - google-chrome
  - spotify
  # The last package I need is "Obsidian", but it is not in the voidlinux repositories. Why?
  # Because: https://github.com/void-linux/void-packages/issues/38348
  # How to fix without flatpak: https://github.com/toluschr/xdeb

cargo_packages:
  - yofi

